"""empty message

Revision ID: 4ad1fcc70278
Revises: 539d44131527
Create Date: 2024-04-18 16:40:22.696819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ad1fcc70278'
down_revision = '539d44131527'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Founders',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('motivation_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['motivation_id'], ['motivations._id'], ),
    sa.PrimaryKeyConstraint('_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Founders')
    # ### end Alembic commands ###
